name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: docker build . --file Dockerfile --tag imail:latest

    - name: Export image
      run: |
        docker save imail:latest | gzip > imail-latest.tar.gz
        echo "filename=imail-latest.tar.gz" >> $GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-image-${{ github.sha }}
        path: imail-latest.tar.gz
        retention-days: 30
